name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

# see https://github.com/lycheeverse/lychee for switch options
# -exclude-all-private    Exclude all private IPs from checking.
#     There is a lot of links to 127.0.0.1 and such in the codebase.
# --exclude-mail
#     lychee is not really meant to parse *py files, so without this option it parses what looks like email addresses to check ttheir validity -- it makes a lot of noise
# --exclude 'https?://localhost'
#     Self explanatory ; localhost without trailing slash so we also exclude things like https://localhost:5000

jobs:
  # TODO : delete one of the two jobs
  # once https://github.com/lycheeverse/lychee/pull/236 will be included in a release, we should be able to not specify the scheme so we can have only one job
  linkCheckerHTTP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Tests often have dummy URL in them, so let's exclude them
      - name: remove tests
        run: rm -fr tests/

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: >
            --exclude-all-private
            --exclude-mail
            --scheme http
            --exclude https?://localhost
            --verbose 
            --no-progress
            **/*.md **/*.py
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report http
          content-filepath: ./lychee/out.md
          labels: report, automated issue

  linkCheckerHTTPS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Tests often have dummy URL in them, so let's exclude them
      - name: remove tests
        run: rm -fr tests/

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: >
            --exclude-all-private
            --exclude-mail
            --scheme https
            --exclude https?://localhost
            --verbose 
            --no-progress
            **/*.md **/*.py
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report https
          content-filepath: ./lychee/out.md
          labels: report, automated issue
